version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Denver
    open-pull-requests-limit: 5
    groups:
      minor-and-patch-gems:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - "dependencies"
      - "automerge"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "dependencies"
